name: ArmorStandController
version: 1.0.0
autor: paul05
main: pack.main
api-version: 1.12.2
commands:
   editarmorstand:
      description: You can edit Armor Stands
      aliases: [eas]
permissions:
   armorstand.edit:
      default: false
      description: Permission to Edit Armor Stands.
